import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-zinc-800">
          <Link href={'/'} className="p-4 text-white">
            Home
          </Link>
          <Link href={'/teams'} className="p-4 text-white">
            Equipos
          </Link>
          <Link href={'/players'} className="p-4 text-white">
            Jugadores
          </Link>
          <Link href={'/matches'} className="p-4 text-white">
            Partidos
          </Link>
        </nav>

        {children}

        <footer className="bg-indigo-800">
          <p className="text-white">Footer</p>
        </footer>
      </body>
    </html>
  );
}
